### ISSUE TITLE
Use case Diagram

### ISSUE THREAD

**Issue by musabd96** [musabd96/Schoolsync#18]

**Comment by Robnoir** [comment]
![Untitled Diagram drawio (1)](https://github.com/musabd96/Schoolsync/assets/112541273/530f8c1d-c070-4a06-b0aa-f82da50bc0a4)


Use case och HML diagram

**Comment by Robnoir** [comment]
![SchoolsyncDiagrams](https://github.com/musabd96/Schoolsync/assets/112541273/176943fb-70d3-48a7-aaea-276564dc640f)

**Comment by Robnoir** [comment]
![NewSchoolsyncDiagrams](https://github.com/musabd96/Schoolsync/assets/112541273/fb8dfd21-f158-4032-af06-9430afbdf10b)
